Metadata:
  StackName: "cost-explorer-cloudformation"
  Tags:
    application: "aws-cost-extractor"
AWSTemplateFormatVersion: 2010-09-09
Resources:
    CostExplorerIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "cost-explorer-iam-role"
        AssumeRolePolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
            - Effect: Allow
              Principal:
                # change the account id as per your account if you need another user/role to assume this role
                AWS: 'arn:aws:iam::1234567890:user/test'
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyDocument:
              Statement:
                - Action:
                    - "ce:GetCostAndUsage"
                  Effect: Allow
                  Resource: "*"
                  Sid: AllowCostExplorerReadApis
            PolicyName: AllowCostExplorerReadApis